In [1]:
# numpy 是所有数据科学，机器学习的基础！！！
# 为什么numpy
# 1.快速
# 2.基于C语言优化
# 3.其他一些Python 数据科学packages的基础

In [2]:
import numpy as np

In [3]:
# numpy的数据类型和属性

In [4]:
# numpy主要的数据类型为narray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1,2,3],
              [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
               [13,14,15],
              [16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [12]:
print(a1.shape,a2.shape,a3.shape)

(3,) (2, 3) (2, 3, 3)


In [14]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [15]:
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [16]:
#  创建array
zero_array = np.zeros((2,2))

In [17]:
zero_array

array([[0., 0.],
       [0., 0.]])

In [18]:
random_array = np.random.randint(0, 10, size=10) # 创建一个随机的整型数组，范围在0到10之间(包含0但不包含10)，size=10表明取10个随机数
random_array

array([0, 7, 7, 6, 7, 1, 6, 2, 1, 8])

In [20]:
# 如果size是一个tuple的话，则会创建不同维度的随机数组，比如下面的例子，会创建3行5列的随机数组
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[1, 5, 0, 8, 1],
       [5, 4, 1, 5, 7],
       [3, 2, 1, 5, 6]])

In [21]:
random_array.shape

(3, 5)

In [27]:
# 除整型随机数组外，还有一般性的随机数组(范围在[0,1)之间)，把randint替换为random即可
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.95108802, 0.01633844, 0.87283188],
       [0.83988743, 0.46403937, 0.86634481],
       [0.86858512, 0.5071557 , 0.5370157 ],
       [0.24284872, 0.61353677, 0.75382099],
       [0.40369379, 0.39388775, 0.14265081]])

In [31]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.46559593, 0.96842287, 0.17012196],
       [0.03661338, 0.17137589, 0.04788894],
       [0.83786876, 0.14391119, 0.17845491],
       [0.74005422, 0.32578483, 0.59488793],
       [0.71155922, 0.13992846, 0.25929923]])

In [ ]:
# 从这里可以看出，random和rand都可以生成一个指定大小的随机数组，但稍存在一些区别
# rand直接使用参数传递大小，而random则是通过size指定大小

# random seed

In [36]:
# 理解，random其实并不是真正的随机，而是由随机种子控制的
# 设置随机种子，保证每次试验的结果一致
np.random.seed(123)
random_array_4 = np.random.rand(5,3)
random_array_4

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971],
       [0.43857224, 0.0596779 , 0.39804426]])

## 观察数组和矩阵

In [37]:
# unique: Find the unique elements of an array.
np.unique(random_array_4)

array([0.0596779 , 0.22685145, 0.28613933, 0.34317802, 0.39211752,
       0.39804426, 0.42310646, 0.43857224, 0.4809319 , 0.55131477,
       0.68482974, 0.69646919, 0.71946897, 0.72904971, 0.9807642 ])

In [38]:
a1

array([1, 2, 3])

In [39]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [41]:
a2[1]

array([4, 5, 6])

In [49]:
random_array_5 = np.random.randint(0,10,size=(1,2,3,4,4))
random_array_5

array([[[[[7, 1, 5, 7],
          [9, 2, 4, 8],
          [1, 2, 1, 1],
          [3, 5, 9, 0]],

         [[8, 1, 6, 3],
          [3, 5, 9, 7],
          [9, 2, 3, 3],
          [3, 8, 6, 9]],

         [[7, 6, 3, 9],
          [6, 6, 6, 1],
          [3, 4, 3, 1],
          [0, 5, 8, 6]]],


        [[[8, 9, 1, 0],
          [3, 1, 3, 4],
          [7, 6, 1, 4],
          [3, 3, 7, 6]],

         [[8, 6, 4, 4],
          [7, 0, 0, 9],
          [8, 8, 4, 8],
          [6, 1, 6, 8]],

         [[7, 9, 1, 7],
          [1, 7, 9, 8],
          [7, 1, 3, 1],
          [8, 7, 5, 1]]]]])

In [50]:
random_array_5.shape, random_array_5.ndim

((1, 2, 3, 4, 4), 5)

In [59]:
random_array_5.shape

(1, 2, 3, 4, 4)

In [66]:
# :从左到右，分别是从最外层到最内层
# 这个例子中，[:, :, :, :2]表示从最内层中取得前2行的数据
random_array_5[:, :, :, :2]

array([[[[[7, 1, 5, 7],
          [9, 2, 4, 8]],

         [[8, 1, 6, 3],
          [3, 5, 9, 7]],

         [[7, 6, 3, 9],
          [6, 6, 6, 1]]],


        [[[8, 9, 1, 0],
          [3, 1, 3, 4]],

         [[8, 6, 4, 4],
          [7, 0, 0, 9]],

         [[7, 9, 1, 7],
          [1, 7, 9, 8]]]]])

## 操作和比较数组array

In [67]:
# 操作包括加、减、乘、除等操作
a1

array([1, 2, 3])

In [70]:
ones = np.ones(3)
twos = ones * 2

In [71]:
twos

array([2., 2., 2.])

In [76]:
a1 / twos

array([0.5, 1. , 1.5])

In [75]:
# // 就是相除之后保留整数部分（删除小数）
a1 // twos

array([0., 1., 1.])

In [77]:
# 取模，相当于Python中 a1 % twos
np.mod(a1, twos)

array([1., 0., 1.])

In [78]:
np.exp(twos)

array([7.3890561, 7.3890561, 7.3890561])

## 数据整合

In [80]:
# np.sum()
massive_data = np.random.rand(100000)

In [82]:
%timeit sum(massive_data)
%timeit np.sum(massive_data)

3.51 ms ± 104 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
13.5 μs ± 20 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [83]:
# mac m3芯片的性能很强大
# 原视频中分别需要17.9毫秒、34微秒

In [84]:
34/13.5

2.5185185185185186

In [85]:
np.mean(a2)

np.float64(3.5)

In [86]:
np.max(a2)

np.int64(6)

In [87]:
np.min(a2)

np.int64(1)

In [88]:
np.std(a2)

np.float64(1.707825127659933)

In [89]:
np.var(a2)

np.float64(2.9166666666666665)

In [90]:
np.sqrt(np.var(a2)) == np.std(a2)

np.True_

In [92]:
high_var_array = np.array([1,5,10,20,100,1000,20000,500000])
low_var_array = np.array([2,4,6,8])

In [93]:
np.var(high_var_array), np.var(low_var_array)

(np.float64(27056646151.75), np.float64(5.0))

In [94]:
#  数据转置
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
a2.shape

(2, 3)

In [100]:
a2_reshape = np.transpose(a2)
a2_reshape

array([[1, 4],
       [2, 5],
       [3, 6]])

In [99]:
a2_reshape.shape

(3, 2)

In [105]:
#  矩阵点乘
np.random.seed(123)
mat1 = np.random.randint(1,5,size=(5,3))
mat2 = np.random.randint(1,5,size=(3,5))
mat1, mat2

(array([[3, 2, 3],
        [3, 1, 3],
        [3, 2, 4],
        [3, 4, 2],
        [3, 2, 1]]),
 array([[2, 3, 4, 2, 1],
        [3, 1, 4, 2, 4],
        [3, 2, 1, 1, 1]]))

In [108]:
np.dot(mat1, mat2)

array([[21, 17, 23, 13, 14],
       [18, 16, 19, 11, 10],
       [24, 19, 24, 14, 15],
       [24, 17, 30, 16, 21],
       [15, 13, 21, 11, 12]])

In [109]:
# 小案例，计算3种武汉小吃在每天的销量以及销售额
np.random.seed(123)
sale_amount = np.random.randint(0,20,size=(5,3))
sale_amount

array([[13,  2,  2],
       [ 6, 17, 19],
       [10,  1,  0],
       [17, 15,  9],
       [ 0, 14,  0]])

In [110]:
# 创建数据框，添加index和column_name
weekly_sales = pd.DataFrame(sale_amount, 
                            index=["周一","周二","周三","周四","周五"],
                            columns=["热干面", "汤面", "炸酱面"])
weekly_sales

热干面  汤面  炸酱面
周一   13   2    2
周二    6  17   19
周三   10   1    0
周四   17  15    9
周五    0  14    0

In [111]:
# 销量已知，需要知道单价，才能求出每天的销售额
unit_price = np.random.randint(1,10,size=(3,1))
unit_price

array([[4],
       [5],
       [1]])

In [112]:
total_price = weekly_sales.dot(unit_price)
total_price

0
周一   64
周二  128
周三   45
周四  152
周五   70

In [113]:
weekly_sales["销售额"] = total_price
weekly_sales

热干面  汤面  炸酱面  销售额
周一   13   2    2   64
周二    6  17   19  128
周三   10   1    0   45
周四   17  15    9  152
周五    0  14    0   70

In [114]:
# 数组排序

In [126]:
random_array = np.random.randint(1,10, size=(2,3,5))
random_array

array([[[4, 4, 8, 7, 9],
        [7, 5, 5, 8, 1],
        [1, 9, 9, 5, 9]],

       [[7, 2, 7, 9, 8],
        [2, 8, 2, 8, 9],
        [8, 2, 4, 2, 9]]])

In [127]:
random_array.shape

(2, 3, 5)

In [128]:
random_array.ndim

3

In [129]:
# sort
# 对数据进行排序，不会影响原数据，参数axis默认为-1，表示会从最后一维进行排序（最后一维应该是最内层二维矩阵的列）
# 即对每一行的各列进行排序
np.sort(random_array,axis=-1)

array([[[4, 4, 7, 8, 9],
        [1, 5, 5, 7, 8],
        [1, 5, 9, 9, 9]],

       [[2, 7, 7, 8, 9],
        [2, 2, 8, 8, 9],
        [2, 2, 4, 8, 9]]])

In [130]:
np.sort(random_array,axis=0) 
# 从数组的第一维进行排序，可以看到，在内层的2维数组的对应位置的各个数字进行排序

array([[[4, 2, 7, 7, 8],
        [2, 5, 2, 8, 1],
        [1, 2, 4, 2, 9]],

       [[7, 4, 8, 9, 9],
        [7, 8, 5, 8, 9],
        [8, 9, 9, 5, 9]]])

In [131]:
np.sort(random_array,axis=1)
# 在此处，对每一列的数据各行进行排序

array([[[1, 4, 5, 5, 1],
        [4, 5, 8, 7, 9],
        [7, 9, 9, 8, 9]],

       [[2, 2, 2, 2, 8],
        [7, 2, 4, 8, 9],
        [8, 8, 7, 9, 9]]])

In [ ]:
# 特别指出，对于二维的数组，axis=-1和axis=1等价
# 理由 (5,3)， -1取的是末尾索引是3；1也取的是第二位索引，也是3

In [132]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [133]:
np.sort(a2, axis=-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [134]:
np.sort(a2, axis=1)

array([[1, 2, 3],
       [4, 5, 6]])

In [135]:
random_array

array([[[4, 4, 8, 7, 9],
        [7, 5, 5, 8, 1],
        [1, 9, 9, 5, 9]],

       [[7, 2, 7, 9, 8],
        [2, 8, 2, 8, 9],
        [8, 2, 4, 2, 9]]])

In [136]:
# Returns the indices that would sort an array.
# 返回排序后得到的顺序索引，参数axis默认为-1，即按照最后一个维度进行排序，最内层二维矩阵的列
np.argsort(random_array)

array([[[0, 1, 3, 2, 4],
        [4, 1, 2, 0, 3],
        [0, 3, 1, 2, 4]],

       [[1, 0, 2, 4, 3],
        [0, 2, 1, 3, 4],
        [1, 3, 2, 0, 4]]])

In [138]:
# 同理argmax和argmin的意思就很清楚了！🫶
np.argmax(random_array)
# 从这里可以看出，如果不指定axis参数，那么numpy会默认将数组平展为一维数组，然后再寻找一维数组中最大值的索引

np.int64(4)

In [139]:
# 若指定axis
np.argmax(random_array, axis=1)
# 从这里可以看出，指定axis=1会把内层的2维数组，寻找每一列中最大值所在行的索引

array([[1, 2, 2, 1, 0],
       [2, 1, 0, 0, 1]])

# 实战训练

<img src = "./images/numpy-panda.jpeg"></img>

In [148]:
from matplotlib.image import imread

# 把一张图片转换为numpy数据格式
panda = imread("./images/numpy-panda.jpeg")

In [149]:
panda.size, panda.shape, panda.ndim

(3271680, (852, 1280, 3), 3)

In [153]:
print(type(panda))

<class 'numpy.ndarray'>
